# Generated by Django 5.1.1 on 2024-10-11 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0003_alter_usuario_contrasena_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='actividad',
            field=models.CharField(choices=[('anclaje', 'Anclaje'), ('configuracion', 'Configuración'), ('fibra_optica', 'Fibra Óptica')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas_empleado', to='brokeAPP.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_hora_actividad',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='brokeAPP.usuario'),
        ),
    ]
