# Generated by Django 5.1.1 on 2024-10-11 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0004_tarea_actividad_tarea_direccion_tarea_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_hora_actividad',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokeAPP.usuario'),
        ),
    ]
