# Generated by Django 5.1.1 on 2024-10-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0005_remove_tarea_actividad_remove_tarea_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='actividad',
            field=models.CharField(choices=[('Anclaje', 'Anclaje'), ('Configuración', 'Configuración'), ('Fibra', 'Fibra')], default='Anclaje', max_length=50),
        ),
        migrations.AddField(
            model_name='tarea',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='empleado_id',
            field=models.CharField(default='No Asignado', max_length=50),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_hora_actividad',
            field=models.DateTimeField(null=True),
        ),
    ]
