# Generated by Django 5.1.1 on 2024-12-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0006_tareaavanzada_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='Cod_postal',
            field=models.CharField(default='Dirección pendiente', max_length=255),
        ),
    ]
