# Generated by Django 5.1.1 on 2024-10-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0007_alter_tarea_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='empleado_id',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_hora_actividad',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
