# Generated by Django 5.1.1 on 2024-10-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0008_remove_tarea_empleado_id_remove_tarea_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
