# Generated by Django 5.1.1 on 2024-10-15 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0009_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokeAPP.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='direccion',
            field=models.CharField(default='Dirección pendiente', max_length=255),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
