# Generated by Django 5.1.1 on 2024-12-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0022_alter_salario_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='fecha_pago',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='pago_actividad',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='total_pago',
        ),
        migrations.RemoveField(
            model_name='salario',
            name='viaticos',
        ),
    ]
