# Generated by Django 5.1.1 on 2024-12-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0023_remove_salario_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salario',
            name='pago_sitio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salario',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salario',
            name='viaticos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
