# Generated by Django 5.1.1 on 2024-12-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0018_alter_notificacion_tarea_alter_notificacion_usuario'),
        ('brokeAPP', '0024_salario_pago_sitio_salario_total_salario_viaticos'),
    ]

    operations = [
    ]
