# Generated by Django 5.1.1 on 2025-01-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0026_alter_tarea_confirmacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salario',
            name='fecha_pago',
        ),
    ]
