# Generated by Django 5.1.1 on 2025-01-08 03:38

from django.db import migrations

def forwards(apps, schema_editor):
    pass  # No realiza ninguna acción porque la columna ya fue añadida manualmente.

class Migration(migrations.Migration):

    dependencies = [
        ('brokeAPP', '0027_remove_salario_fecha_pago'),  # Ajusta la dependencia si es necesario
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
